version: '3.8'
 
services:
  db:
    image: mysql:8.0.33
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: sankey
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
 
volumes:
  db_data:
